### ISSUE TITLE
Mailabfrage in Textfeld unvollständig

### ISSUE THREAD

**Issue by s1nlows** [termify/termify#2]
Auch unvollständige Mailadressen wie test@gmail werden akzeptiert. Es erfolgt keine Überprüfung auf Vollständigkeit.
Es ist für das System gleich, da der Nutzer ja ein Interesse hat, dass eine valide Mail-Adresse hinterlegt wird, aber dadurch wird es für Bots leichter, die Kriterien für Massenabfragen zu erfüllen und eine tatsächliche Anmeldung durch Überlast zu verhindern.

**Comment by edlixstudios** [comment]
Email Validation sollte nun funktionieren
