### ISSUE TITLE
Loginvorgang ist mit nicht bestätigter Mailadresse möglich

### ISSUE THREAD

**Issue by termify** [termify/termify#21]
Die konstruierte Testmail "sdfe@bla" für die Abfragen erstellt worden. Die kann nicht bestätigt werden, ein Anmelden funktioniert trotzdem.

**Comment by edlixstudios** [comment]
Das hatte funktioniert da ich es händisch auf Supabase freigeschaltet habe. Ich habhe es nochmals gegen geprüft, nicht bestätigte Emails können sich nicht einloggen, daher Close
