### ISSUE TITLE
Buchungsbestätigungsmail bleibt aus

### ISSUE THREAD

**Issue by termify** [termify/termify#26]
Entgegen der Mitteilung der Buchungsbestätigung wird keine Mail verschickt bzw. es wird keine empfangen, da der Kalender nicht im Profil, sondern frei ohne Anmeldung hinterlegt ist.

**Comment by edlixstudios** [comment]
Wir werden im Rahmen des Studium Projekt keine Buchungsbestätigung via Mail senden, da wir keinen Mailing Server besitzt.  Der kostet Geld und ich habe leider keinen kostenlosen gefunden. Sollte sich das die Tage noch ändenrn, werde ich einbauen
