### ISSUE TITLE
Wiederholte Buchungen über selben Account erzeugen keine weiteren Bestätigungsmails

### ISSUE THREAD

**Issue by termify** [termify/termify#34]
Nachdem eine Buchung vollständig absolviert und eine Bestätigungsmail (auch wenn diese leer sind) versandt wurde, bleiben bei weiteren Buchungen innerhalb der gleichen Login-Session ohne Bestätigung durch Mail.
Logoutvorgang und erneuter Login beheben das Problem nicht.

**Comment by edlixstudios** [comment]
Welche Bestätigungsmails erhälst du? 😅 Wir senden keine Mail bei Buchung
